### ISSUE TITLE
.NET Standard < 2.0

### ISSUE THREAD

**Issue by cwharris** [ektrah/nsec#1]
Have you considered releasing pre .NET Standard 2.0?

The .NET Core roadmap states 2.0 release is slated for Q3 2017, and this seems like an aweful long time to wait. I'm building a .NET Core Discord client (I am aware of Discord.NET - this is different), and would love to use this library.

https://github.com/dotnet/core/blob/master/roadmap.md

**Comment by ektrah** [comment]
NSec runs on .NET Core 1.1, but uses new features (namely slices) that are unlikely to ship for .NET Core 1.1 before the .NET Core 2.0 release. I plan to make a pre-release of NSec as soon as things begin to stabilize, but there probably won't be a 1.0 release of NSec before Q3 2017. I'm painfully aware that this is an awful long time to wait.

**Comment by andymac4182** [comment]
Any chance of a pre-release before .NET Core 2.1? It would be great to be able to start looking at it now.

**Comment by ektrah** [comment]
VS 15.5 and the .NET 2.1 SDK (which does not include the .NET 2.1 Runtime) have been released now, but `Span<T>` and `ReadOnlySpan<T>` are currently still only available as nightly builds. If you want, you can try out a nightly build of NSec by getting it from [here](https://www.myget.org/feed/nsec/package/nuget/NSec.Cryptography) and its dependencies from [here](https://dotnet.myget.org/gallery/dotnet-core).

**Comment by andymac4182** [comment]
I must of miss read the release notes of VS 15.5 I thought it had included all the C# 7.2 features as usable now.

**Comment by ektrah** [comment]
The C# compiler support for  `Span<T>` and `ReadOnlySpan<T>` is done, but the actual implementations of `Span<T>` and `ReadOnlySpan<T>` are still being worked on.

**Comment by ektrah** [comment]
A pre-release version of NSec [is now available](https://nsec.rocks/docs/install).

There will be a stable release once the [System.Memory](https://www.nuget.org/packages/System.Memory/) package leaves the preview status.
