### ISSUE TITLE
Public Key Formarter not to spec

### ISSUE THREAD

**Issue by dolphinsd** [ektrah/nsec#10]
Here is reference to widely used library in Java.
https://github.com/str4d/ed25519-java/blob/master/src/net/i2p/crypto/eddsa/EdDSAPublicKey.java

Their public formater seems to be different:
from your implementation of s_pkixPublicKeyFormatter

Also how does one gets various elements, like group A as in Java implementation.

**Comment by dolphinsd** [comment]
@ektrah, I happy to share entire project that is trying to use your library. What is the best way?

**Comment by ektrah** [comment]
You can contact me at mailto:contact@nsec.rocks. However, I would prefer an example of a public key or a minimal code example being posted here to digging through an entire project.

**Comment by dolphinsd** [comment]
after all I try raw key output and it the same as group A key
