### ISSUE TITLE
Secure private key with passphrase when exporting

### ISSUE THREAD

**Issue by dolphinsd** [ektrah/nsec#11]
Once private key is exported is not secure. 

Proposal to add ability to encrypt the private key using a symmetric encryption key derived from a passphrase and then decrypted again.

**Comment by dolphinsd** [comment]
@ektrah it could be an option to Export call?

**Comment by ektrah** [comment]
An experimental implementation has been added in [PasswordBasedKeyExporter.cs](https://github.com/ektrah/nsec/blob/2df8892a956ebde70751c294a502d280e8bf891c/src/Experimental/PasswordBased/PasswordBasedKeyExporter.cs). I'm not sure how useful it is (and it's probably coming way too late too; sorry for that). Feedback is welcome.
