### ISSUE TITLE
Can this library be used as foundation for a bitcoin library

### ISSUE THREAD

**Issue by MithrilMan** [ektrah/nsec#15]
bitcoin uses RIPEMD160, SHA256, ECDSA on Secp256k1 curve
Does this library support these algorithms?

**Comment by ektrah** [comment]
Simple question, simple answer: No.

**Comment by MithrilMan** [comment]
It's a pity, I'd like to see some of these implementation using ReadOnlySpan stuff, BouncyCastle is a bit behind on that and I'm looking for alternatives.

Any plan to implement any of these stuff or is it out of scope for this project?

**Comment by ektrah** [comment]
NSec doesn't implement any cryptographic algorithms itself but relies on [libsodium](http://libsodium.org/), which has no plans for adding support for RIPEMD160 or ECDSA.

**Comment by MithrilMan** [comment]
ok thanks for the clarification
