### ISSUE TITLE
NSEC on Xamarim Forms - Platform Not Supported

### ISSUE THREAD

**Issue by llustosa** [ektrah/nsec#16]
Hi,
I'm trying to use NSec with Xamarin Forms, but I'm having some trouble. The library doesn't load. 
Anybody can help me, please?
Thanks

System.TypeInitializationException: The type initializer for 'BizPay.Crypto.CryptoHelper' threw an exception. ---> System.PlatformNotSupportedException: Could not initialize platform-specific components. NSec may not be supported on this platform. See https://nsec.rocks/docs/install for more information. ---> System.DllNotFoundException: libsodium\n  at (wrapper managed-to-native) Interop+Libsodium.sodium_library_version_major()\n  at NSec.Cryptography.Sodium.InitializeCore () [0x00000] in <ba1701410b96469f9e9378cadfef57a0>:0 \n   --- End of inner exception stack trace ---\n  at NSec.Cryptography.Sodium.InitializeCore () [0x0003e] in <ba1701410b96469f9e9378cadfef57a0>:0 \n  at NSec.Cryptography.Sodium.Initialize () [0x00007] in <ba1701410b96469f9e9378cadfef57a0>:0 \n  at NSec.Cryptography.Algorithm..ctor () [0x00006] in <ba1701410b96469f9e9378cadfef57a0>:0 \n  at NSec.Cryptography.SignatureAlgorithm..ctor (System.Int32 privateKeySize, System.Int32 publicKeySize, System.Int32 signatureSize) [0x00000] in <ba1701410b96469f9e9378cadfef57a0>:0 \n  at NSec.Cryptography.Ed25519..ctor () [0x00000] in <ba1701410b96469f9e9378cadfef57a0>:0 \n  at NSec.Cryptography.SignatureAlgorithm.get_Ed25519 () [0x00009] in <ba1701410b96469f9e9378cadfef57a0>:0 \n  at BizPay.Crypto.CryptoHelper..cctor () [0x00000] in /Users/leandrolustosa/Documents/BizWallet/BizPay/BizPay/Crypto/CryptoHelper.cs:13 \n   --- End of inner exception stack trace ---\n  at BizPay.ViewModels.WalletViewModel+<ExecuteSendTxCommand>d__26.MoveNext () [0x001fd] in /Users/leandrolustosa/Documents/BizWallet/BizPay/BizPay/ViewModels/WalletViewModel.cs:92 \n--- End of stack trace from previous location where exception was thrown ---\n  at BizPay.ViewModels.WalletViewModel+<ExecuteSendTxCommand>d__26.MoveNext () [0x000cb] in /Users/leandrolustosa/Documents/BizWallet/BizPay/BizPay/ViewModels/WalletViewModel.cs:78 "

**Comment by ektrah** [comment]
NSec is not supported on this platform.
