### ISSUE TITLE
ref struct `PublicKey`?

### ISSUE THREAD

**Issue by NickStrupat** [ektrah/nsec#24]
I have a blockchain-ish use case where I am signing and verifying data in a byte buffer, which includes storing the public key adjacent to the signature.

Verification is the common operation. With the public key being stored, it would be ideal to be able to verify without having to hit the GC to instantiate a `PublicKey` for verification.

I haven't had a chance to dive into the class to see if there are any blockers to switching to `ref struct`, but I'm wondering what you think in the meantime?

**Comment by ektrah** [comment]
Avoiding that allocation would be fully in line with the goals of NSec. I don't think there would be any blockers from the implementation side. However, switching from `class` to `struct` would be a major breaking change.

One of the reasons why `PublicKey` is a `class` is that it can be used e.g. as the `TKey` of a `Dictionary<TKey, TValue>`.

**Comment by NickStrupat** [comment]
I agree it would be a breaking change.

`struct`s can indeed be used as the `TKey` of a `Dictionary<TKey, TValue>`. However, `ref struct`s cannot.

What about an overload of `Verify` which accepts a `ReadOnlySpan<Byte>` along with `KeyBlobFormat`. It would run the `PublicKey` import code without actually allocating.

**Comment by ektrah** [comment]
After thinking about this for a while (and apologies for taking so long), I'm not sure if changing PublicKey into a struct is a good idea. Structs of this size are generally [discouraged](https://stackoverflow.com/q/1082311) and ref structs cannot be dictionary keys.

An overload that accepts a blob and a KeyBlobFormat might be an option. The CLR is usually quite good at quickly allocating and deallocating small objects, though. And there would still be the overhead of validating and deserializing the blob. I'm not sure if there'd be a big performance improvement and if that justifies making the API more cluttered. 

I'm closing this issue for now. Feel free to re-open if you disagree. 😃
