### ISSUE TITLE
PasswordBasedKeyDerivationAlgorithm in main lib?

### ISSUE THREAD

**Issue by haf-afa** [ektrah/nsec#27]
Question: how come the Argon2i function/scrypt functions from https://libsodium.gitbook.io/doc/password_hashing/the_argon2i_function are not exposed in the main library? It would be very useful and they are seemingly passing their tests?

**Comment by ektrah** [comment]
The password-based algorithms API still needs a bit of thinking. In particular, it's a bit unclear how the selection of parameters should be done best and how to deal with resource exhaustion (out-of-memory errors).

Another issue is that the [Argon2 RFC](https://datatracker.ietf.org/doc/draft-irtf-cfrg-argon2/) is still stuck at draft stage.

And, last but not least, the API documentation has not been written yet.

**Comment by haf-afa** [comment]
> selection of parameters should be done best

Can't this be improved as you go? Starting with parameters as they are in the unit tests?

> how to deal with resource exhaustion

For .Net, you have a global singleton OutOfMemoryException, but normally your process gets killed before you ever see it (if you're running a server/docker container). So unless you're planning on doing manual memory management with p/invoke, I'd say it's hard to explicitly handle OOM errors on .Net,
