### ISSUE TITLE
PublickKey Equals method can throw "Object reference not set to an instance of an object."

### ISSUE THREAD

**Issue by bugbytesinc** [ektrah/nsec#28]
The `Equals` method implemented on `PublicKey` (/src/Cryptography/PublicKey.cs, Line 67) does not appear to check for null prior to checking for the equality of algorithm (line 78).  This can result in an "Object reference not set to an instance of an object." exception thrown.  The "object" version of the Equals method (line 97) uses an "obj as PublicKey" cast to this method, which is one example of how null can be passed into the method to start with.

Discovered this error when using an array of public keys in a windows WPF application, the change detection algorithim was enumerating keys to determine if it was necessary to update, a portion of the stack trace follows:
```
Object reference not set to an instance of an object.

   at NSec.Cryptography.PublicKey.Equals(PublicKey other)
   at NSec.Cryptography.PublicKey.Equals(Object obj)
   at System.Windows.Controls.ItemsControl.EqualsEx(Object o1, Object o2)
   at System.Windows.Data.BindingExpression.OnDataContextChanged(DependencyObject contextElement)
```

**Comment by ektrah** [comment]
Good catch! Thanks a lot for reporting this. Fixed in https://github.com/ektrah/nsec/commit/653ad7b0e1cf00d51c20c792db79b2504ddd32a9.
