### ISSUE TITLE
Struggling to compile the solution

### ISSUE THREAD

**Issue by mlaily** [ektrah/nsec#3]
Hi,

I'd like to play with the code, but I'm struggling trying to compile it.

In particular, it seems the two nuget dependencies cannot be restored. (System.Memory [4.5.0-preview2-26228-08] and System.Runtime.CompilerServices.Unsafe [4.5.0-preview2-26228-08])
I suspect this is because these are pre-release versions that are not yet available on nuget.org.

I see in the build script some references to dotnet.myget.org, but simply adding this package source in my visual studio does not seem to resolve the issue...

Could offer some guidance please?

(And in the future, I suggest you adhere to the [F5 manifesto](https://www.khalidabuhakmeh.com/the-f5-manifesto-for-net-developers), if at all possible :) )

Thank you.

**Comment by mlaily** [comment]
Well. It seems I created this issue a bit too fast.

I replaced https://dotnet.myget.org with https://dotnet.myget.org/F/dotnet-core/api/v3/index.json and it works. I wasn't aware myget.org supported different feeds.

I' closing this issue, but I still suggest you document these kind of things explicitely, in your contributing guide for example.

Cheers.

**Comment by ektrah** [comment]
The System.Memory and System.Runtime.CompilerServices.Unsafe packages are still under development. Therefore, building NSec from sources is a bit tricky right now. This will fix when the two packages leave the preview status.

For now, the best way to try out NSec is to [get it from nuget.org](https://www.nuget.org/packages/NSec.Cryptography/18.2.0-preview1). This specific preview version depends on System.Memory and System.Runtime.CompilerServices.Unsafe package versions that are available from nuget.org as well, so you shouldn't have to add any additional feeds.

Thanks for suggestion the F5 manifesto. That looks like good advice.
