### ISSUE TITLE
'The key BLOB format 'RawPublicKey' is not supported by the specified algorithm.

### ISSUE THREAD

**Issue by jonhack** [ektrah/nsec#34]
I hate to open an issue as I'm not convinced there's actually an issue with the library. More likely than not I'm using it incorrectly but I can't find documentation to set me on the right path.

I'm attempting to do some code-signing using ed25519. I've made a console app that allows me to create a key and write both the private and public keys to files. Then it moves on and does the code-signing and verification successfully. I can also tell it to read the existing keys from the files, and use them to sign/verify.

My issue is that when I attempt to Import the public key from the file, it fails with the error: 
**'The key BLOB format 'RawPublicKey' is not supported by the specified algorithm.**

I've tried changing the key blob format, and I receive the same error with every one. The file is written, and it reads, correctly. 

I've looked at https://github.com/ektrah/nsec/blob/master/src/Cryptography/Ed25519.cs and I see that all 4 of the KeyBlobFormats are supposed to be accepted. 

I'd appreciate any direction you can give me on this one.

Here's the code I use to export and then import:

```
      _algorithm = SignatureAlgorithm.Ed25519;
      var creationParameters = new KeyCreationParameters
      {
        ExportPolicy = KeyExportPolicies.AllowPlaintextArchiving        
      };

      _key = new Key(algorithm, creationParameters);

      //Export Private Key
      var prkBlob = _key.Export(KeyBlobFormat.RawPrivateKey);
      File.WriteAllBytes($"{_keyFilename}.prk", prkBlob);

      //Export Public Key
      var pukBlob = _key.Export(KeyBlobFormat.RawPublicKey);
      File.WriteAllBytes($"{_keyFilename}.puk", pukBlob);


      //Import Private Key
      var prkBlobImport = File.ReadAllBytes($"{_keyFilename}.prk");
      Key.TryImport(_algorithm, prkBlobImport, KeyBlobFormat.RawPrivateKey, out _key, in creationParameters);

      //Import Public Key
      var pukBlobImport = File.ReadAllBytes($"{_keyFilename}.puk");
      Key.TryImport(_algorithm, prkBlobImport, KeyBlobFormat.RawPublicKey, out _key, in creationParameters);
```

After the last line executes, it gives the error I've mentioned above:
**'The key BLOB format 'RawPublicKey' is not supported by the specified algorithm.**

I'd love to know if I'm using it wrong, or if there's an underlying issue in the library.
Cheers.

**Comment by ektrah** [comment]
No worries; all issues are welcome :smile:

The mystery is quite easy to solve: You're trying to import a public key using `Key.Import`, but the `Key` class represents private keys. Have a look at `PublicKey.Import` instead. (Maybe it's not helpful that one can export the public key via `Key.Export`... I should probably remove that in favor of the existing `PublicKey.Export` method.)

I would recommend the PkixPublicKeyText format, by the way. This is a standard format (PEM) supported by many, many cryptographic libraries and tools (though not all of those support Ed25519; but the format also used e.g. for RSA keys).

**Comment by Orbis25** [comment]
Hi i have a similar problem.

**Comment by ektrah** [comment]
@Orbis25 It seems you're trying to import your two Base64 strings as ChaCha20-Poly1305 keys and then use them with the X25519 algorithm. If the Base64 strings are actually X25519 private/public keys, you need to import them as such:

```csharp
var algorithm = KeyAgreementAlgorithm.X25519;
using var key = Key.Import(algorithm, ..., KeyBlobFormat.RawPrivateKey);
var otherPartyPublicKey = PublicKey.Import(algorithm, ..., KeyBlobFormat.RawPublicKey);
using var sharedSecret = algorithm.Agree(key, otherPartyPublicKey);
...
```

(I'd recommend using the PkixPrivateKey(Text) and PkixPublicKey(Text) formats with X25519, though, if possible.)

Please open a new issue if the problem persists.
