### ISSUE TITLE
System.ArgumentException: 'The specified key is for algorithm 'NSec.Cryptography.ChaCha20Poly1305'. Expected 'NSec.Cryptography.ChaCha20Poly1305'. 

### ISSUE THREAD

**Issue by matt1tk** [ektrah/nsec#37]
So confused by this error. As far as I can tell it is none of these issues: 
ArgumentException
    key.Algorithm is not the same object as the current AeadAlgorithm object. (both are ChaCha20Poly1305)
ArgumentException
    nonce.Size is not equal to NonceSize. (don't care about nonce usage, just test encrypting a message. and the exception doesn't mention the nonce)
ArgumentException
    plaintext.Length plus TagSize is greater than int.MaxValue. (it's just "hello")

Here is my code:

```
            var algorithm = KeyAgreementAlgorithm.X25519;
            using var alice = Key.Create(algorithm);
            using var bob = Key.Create(algorithm);
            var aliceSharedSecret = KeyAgreementAlgorithm.X25519.Agree(alice, bob.PublicKey);
            var bobSharedSecret = KeyAgreementAlgorithm.X25519.Agree(bob, alice.PublicKey);
            var aliceSharedSecretKey = KeyDerivationAlgorithm.HkdfSha512.DeriveKey(aliceSharedSecret!, ReadOnlySpan<byte>.Empty, ReadOnlySpan<byte>.Empty, new ChaCha20Poly1305());
            var bobSharedSecretKey = KeyDerivationAlgorithm.HkdfSha512.DeriveKey(bobSharedSecret!, ReadOnlySpan<byte>.Empty, ReadOnlySpan<byte>.Empty, new ChaCha20Poly1305());
            Console.WriteLine(aliceSharedSecretKey.Algorithm);
            Console.WriteLine(bobSharedSecretKey.Algorithm);
            var encryptedString = AeadAlgorithm.ChaCha20Poly1305.Encrypt(aliceSharedSecretKey, new Nonce(ReadOnlySpan<byte>.Empty, 1), ReadOnlySpan<byte>.Empty, Encoding.UTF8.GetBytes("Hello").AsSpan());
            var encryptedString2 = AeadAlgorithm.ChaCha20Poly1305.Encrypt(bobSharedSecretKey, new Nonce(ReadOnlySpan<byte>.Empty, 2), ReadOnlySpan<byte>.Empty, Encoding.UTF8.GetBytes("Hello").AsSpan());
            Console.WriteLine(Convert.ToBase64String(encryptedString));
            Console.WriteLine(Convert.ToBase64String(encryptedString2));
```

I have a feeling it's something to do with my implementation, but the exception message is quite non-descriptive.

**Comment by ektrah** [comment]
The exception message indeed is a bit confusing. The issue is this one:

> key.Algorithm is not the same object as the current AeadAlgorithm object. (both are ChaCha20Poly1305)

In your code, you're using `new ChaCha20Poly1305()` when creating the key and `AeadAlgorithm.ChaCha20Poly1305` when encrypting. Even through you're using `ChaCha20Poly1305` instances in either case, they're not the same instance.

You can fix the issue by assigning `new ChaCha20Poly1305()` to a variable and use that for both key creation and encryption, or by using the instance returned by `AeadAlgorithm.ChaCha20Poly1305` in either case.

I've tried to improve the exception message in a1e4c1b37a86d88a97e15c97e243d7451e685df1.

**Comment by matt1tk** [comment]
Thanks, closing

**Comment by matt1tk** [comment]
@ektrah I am getting this even when using AeadAlgorithm.ChaCha20Poly1305 instead of a variable. https://pastebin.com/CCGpxAN9

**Comment by matt1tk** [comment]
never mind 😞 i am blind https://i.imgur.com/S5jCYnC.png
