### ISSUE TITLE
Possible to create a single key that can both sign and derive a shared secret/key?

### ISSUE THREAD

**Issue by matt1tk** [ektrah/nsec#38]
As far as I can tell you cannot sign with X25519, and you cannot generate a shared secret and key with Ed25519. I do not want to create 2 different keys, if possible. Thanks!

**Comment by matt1tk** [comment]
Well I'm not sure if the issue I specifically mentioned is possible, but for what I'm doing I realized I can simply generate an ephemeral X25519 keypair, sign it with the long term Ed25519 keypair, and on each end exchange ephemeral X25519 public keys, then from THAT generate a shared secret. And it's probably in the best interest to not have a signing and encrypting key be the same. For now I am closing it. :)

**Comment by ektrah** [comment]
Which specification are you implementing?

**Comment by matt1tk** [comment]
Currently not a set-in-stone specification, just looking to sort of duplicate the [scuttlebutt protocol's decentralization and key system](https://ssbc.github.io/scuttlebutt-protocol-guide/) and [the whisper protocol](https://eth.wiki/concepts/whisper/whisper). 

Essentially, I would want a single Ed25519 key to be the identity for a single person. Say Alice wants to talk to Bob. They both have each other's public keys (maybe a DHT-type system for public keys). Locally whenever a new username is registered or when they first connect, everyone calculates the shared secret between them and each user. That way, when something encrypted gets delivered, each user who sees it will firstly forward it on to other nodes, then try to decrypt it with each shared secret they have. From what I can tell you cannot calculate Ed25519 key shared secrets nor sign with X25519, so I may just have to make an Ed25519 and X25519 keypair and add them both.

**Comment by ektrah** [comment]
[It seems](https://ssbc.github.io/scuttlebutt-protocol-guide/#starting-keys) that Scuttlebutt is using static, long-term Ed25519 keys and ephemeral, short-term X25519 keys. So I don't see a need for keys that can both sign and perform key agreement here, or a need to distribute more than one public key. Maybe you could do the same?

**Comment by matt1tk** [comment]
This would require signing the short term X25519 public key. I'm looking to reduce such metadata in a system like eth's whisper where every node gets every message. It would divulge that X wants to talk to another user since X signed a keypair. However ultimately I will have to use both X25519 and Ed25519, seems like that is inevitable.

**Comment by ektrah** [comment]
While it's technically possible to convert an Ed25519 key to a Curve25519 key, there are a number of security considerations related to using the same key for multiple purposes. So you could create two Ed25519 keys and then convert one of them to Curve25519, but that probably doesn't provide an advantage over creating an Ed25519 key and a Curve25519 key from the start. For this reason, NSec currently doesn't expose a method for converting keys.

**Comment by matt1tk** [comment]
Thanks!
