### ISSUE TITLE
NSec and Unity 3D

### ISSUE THREAD

**Issue by Kirbyrawr** [ektrah/nsec#40]
Hi there, this is not an issue but rather a solution to a problem i had and i was thinking of share here to keep in the closed issues historic for future references.

I managed to make NSec work in Net Standard 2.0 under Unity 3D with some modifications and compiling the Libsodium libraries.
Here is the repo with the branch in case anyone needs, it's based in the version 19.5.0 but i think there is no issue with updating to the latest if anyone needs it.

https://github.com/Kirbyrawr/nsec-unity/tree/19.5.0-unity

Tried in Android and PC and works ok, should work for the rest of the platforms considering the Libsodium libraries are there.

**Comment by ektrah** [comment]
Nice work! And nice to see that NSec seems to work almost out-of-the-box with Unity 3D.

What do you think is the best next step?

**Comment by Kirbyrawr** [comment]
Hi, at the moment i have compiled the Libsodium libraries in another
repositories and seems to work for the different platforms, if you want to
close this issue feel free, about the next steps i think it will be keeping
it a bit updated maintained with your base (thanks for it), i think i will
also upload it as a upm (unity package) citing your repository and your
license obviously, so this way other plugins can use it.

**Comment by Kirbyrawr** [comment]
Hi there from now the users can install version 19.5.0 from Unity itself via Package Manager (npm custom scope)
![Screenshot 2020-10-18 at 01 34 03](https://user-images.githubusercontent.com/3259762/96355451-0d7ed000-10e2-11eb-994a-a9ae045eda9b.png)

I will be sure to fill all the details properly and credit your repository in the description apart from the license, thanks!

**Comment by Kirbyrawr** [comment]
https://github.com/Kirbyrawr/nsec-unity

**Comment by ektrah** [comment]
Is there any way the platform-specific compiled libsodium libraries could be included in the [libsdium NuGet package](https://www.nuget.org/packages/libsodium/)? Or can Unity not use native libraries from NuGet packages at all?

**Comment by Kirbyrawr** [comment]
Hi Ektrah, the compiled libraries are inside another package, i can add
them as dependency so when you install NSec it does install the required
libs. Is that ok?

**Comment by Kirbyrawr** [comment]
I don't use Nuget but npm in Unity that's why i needed to upload the repos
in github.

**Comment by ektrah** [comment]
I see. So it's really a separate infrastructure. I will close this issue, since it doesn't seem there is anything to do. Thanks a lot for your work!

**Comment by Kirbyrawr** [comment]
Yeah, all is done, thank you!
