### ISSUE TITLE
Request: Ed448/X448

### ISSUE THREAD

**Issue by sigaloid** [ektrah/nsec#41]
https://tools.ietf.org/html/rfc7748#section-6.2

Bit overkill, but assume performance isn't an issue.

**Comment by ektrah** [comment]
NSec doesn't implement any cryptographic primitives itself but relies on libsodium for that. At present, libsodium doesn't include an Ed448/X448 implementation, so I'm closing this issue for now. Feel free to reopen if libsodium adds support.

**Comment by sigaloid** [comment]
Thought libsodium did have that :cry: thanks!
