### ISSUE TITLE
Request: XChaCha20

### ISSUE THREAD

**Issue by sigaloid** [ektrah/nsec#42]
https://doc.libsodium.org/advanced/stream_ciphers/xchacha20

Already exists in libsodium, would be nice to not have to worry about nonces.

**Comment by ektrah** [comment]
Are you referring to XChaCha20 or XChaCha20-Poly1305?

XChaCha20 is an unauthenticated stream cipher; I don't see a strong need to have that in NSec. Do you have a specific use case in mind?

XChaCha20-Poly1305 as an AEAD algorithm would make a lot of sense to add to NSec. It's currently already part of the NSec.Experimental package. I'm still hoping for the IETF draft specification (*draft-irtf-cfrg-xchacha*) to progress a bit more before adding it to the main package.

**Comment by sigaloid** [comment]
Thanks, looking at the NSec.Experimental for right now. (and yeah I meant the AEAD)
