### ISSUE TITLE
Plans to support libsodium Key Exchange API?

### ISSUE THREAD

**Issue by enclave-marc-barry** [ektrah/nsec#48]
Libsodium's [crypto_kx_client_session_keys()](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_kx/crypto_kx.c#L34) function wrap calls to `crypto_scalarmult` and `crypto_generichash` in to a single place to provide `tx` and `rx` keys using Blake2b and is quite distinct from the existing `KeyAgreementAlgorithm` and `KeyDerivationAlgorithm` classes in NSec.

Are there any plans to support the libsodium [key exchange](https://libsodium.gitbook.io/doc/key_exchange) API in NSec?

**Comment by ektrah** [comment]
The libsodium Key Exchange API seems to use a custom solution based on BLAKE2B-512 where protocols like TLS typically use HKDF to derive session keys. Support for HKDF is included in NSec, so at present I don't have plans to add support for the libsodium API.

**Comment by enclave-marc-barry** [comment]
Ok, thanks for clarifying. Would you be open to receiving a PR to add support for this API?

**Comment by ektrah** [comment]
For experimentation, yes, I would be open to receiving a PR that adds support for this API to the NSec.Experimental package. However, before adding it to NSec itself, I think it would be good to have a stable, reviewed specification as well as test vectors that have been validated against other implementations.

**Comment by ektrah** [comment]
A PR that adds an API to NSec.Experimental would still be welcome, but I don't plan to work on this, so I'm closing this for now.
