### ISSUE TITLE
Having trouble encrypting through stdin/out

### ISSUE THREAD

**Issue by matt1tk** [ektrah/nsec#49]
I am having trouble encrypting a stream of data being read from stdin. I want to have it sit between opening and reading a file. For example, `cat test.txt | dotnet encrypt.dll > encrypted.txt` or `cat encrypted.txt | dotnet decrypt.dll > decrypted.txt`. 

However, every stdin/out code snippet I find for c# uses 2048 byte buffers. For example: 
```
using (Stream stdin = Console.OpenStandardInput())
                using (Stream stdout = Console.OpenStandardOutput())
                {
                    byte[] buffer = new byte[2048];
                    int bytes;
                    while ((bytes = stdin.Read(buffer, 0, buffer.Length)) > 0)
                    {
                        stdout.Write(encrypt_method(buffer), 0, bytes);
                    }
                }
```
 I have it encrypting each chunk of 2048 individually, but it simply fails the decryption bool. I assume it has to do with the 2048 byte chunks, since it works fine if I read the whole file into memory. I'm quite confused, since each 2048 bytes is its own bit of encrypted data. I'm thinking maybe the 2048 byte input is outputting extra bytes for the authentication, causing the input to still read by 2048 bytes, failing. I got that it outputs 2064 bytes, which is 16 bytes for the poly1305. But when I input in chunks of 2064 through stdin, it still fails though. Is there a way to forgo the Poly1305? I have already ignored the nonce, since it would be a hassle with the chunk system. Alternatively, is there a better way for me to encrypt/decrypt a stream of data with this method?

**Comment by ektrah** [comment]
Stream encryption is tricky. It's not enough to just encrypt one block after another; for example, you also need to ensure that those blocks are actually part of the same file. Getting the keys and the nonces right is critical for security. And those 16 extra bytes are **not** optional.

NSec currently doesn't provide a method for stream encryption. You could read the entire stdin into a single byte array and then encrypt that, but even that requires that you get the key and the nonce right. So, I'd recommend that you don't attempt to invent anything here by yourself; instead, I'd look for the specification of a standard for file encryption that defines exactly how to split up the file, manage the keys, and construct the nonces.

**Comment by matt1tk** [comment]
I tried to read in chunks of 2064 bytes as well, but it failed. This program would just sit between pipes on my local machine, it's not mission critical. I just don't know why even reading in chunks of 2064 didn't work either, because as I understand it, that should have worked. Thanks
