### ISSUE TITLE
The key BLOB format 'RawPublicKey' is not supported by the specified algorithm ChaCha20Poly1305

### ISSUE THREAD

**Issue by Orbis25** [ektrah/nsec#61]
I am new to using these cryptographic algorithms, maybe I am doing something wrong ..

Hi i have a problem, i want encrypt and decrypt data using ChaCha20Poly1305... and a SharedSecret with a public/private key but i have a error when import a public key
  

        public EService()
        {
            var _algoritm = new ChaCha20Poly1305();

            var privateKey = Convert.FromBase64String("base64string");
            var publicKey = Convert.FromBase64String("base64string");

            var _privateKey = Key.Import(_algoritm, privateKey, KeyBlobFormat.RawSymmetricKey);

          **/// same bug here!**
           var  _publicKey = PublicKey.Import(_algoritm, publicKey, KeyBlobFormat.RawSymmetricKey);

           var  _box = KeyAgreementAlgorithm.X25519.Agree(_privateKey, _publicKey);

         var   _derived = KeyDerivationAlgorithm.HkdfSha512.DeriveKey(_box, ReadOnlySpan<byte>.Empty,
                        ReadOnlySpan<byte>.Empty, AeadAlgorithm.ChaCha20Poly1305,
                        new KeyCreationParameters
                        {
                            ExportPolicy = KeyExportPolicies.AllowPlaintextArchiving
                        });
        }

**Comment by Orbis25** [comment]
help please.

**Comment by ektrah** [comment]
It seems you're trying to import your two Base64 strings as ChaCha20-Poly1305 keys and then use them with the X25519 algorithm. If the Base64 strings are actually X25519 private/public keys, you need to import them as such:

```csharp
var algorithm = KeyAgreementAlgorithm.X25519;
using var key = Key.Import(algorithm, ..., KeyBlobFormat.RawPrivateKey);
var otherPartyPublicKey = PublicKey.Import(algorithm, ..., KeyBlobFormat.RawPublicKey);
using var sharedSecret = algorithm.Agree(key, otherPartyPublicKey);
...
```

(BTW, I'd recommend using the PkixPrivateKey(Text) and PkixPublicKey(Text) formats with X25519, if possible.)

**Comment by Orbis25** [comment]
1 - if you used that algorithm as encryption of the information?
Because the class * X25519 * has no method of Encrypt or decrypt.

2 - Because I just couldn't do the following:
var cyphertext = AeadAlgorithm.ChaCha20Poly130.Encrypt(sharedSecret, nonce, new byte [0], message);

what I want is to encrypt and decrypt information using the ChaCha20-Poly1305 algorithm and a public and private key.

Sorry I'm new to this maybe I'm misinterpreting the usage. 🙌

**Comment by ektrah** [comment]
I get this might be a bit confusing for newcomers as NSec unfortunately doesn’t come with a lot documentation on how solve common problems with it. 

For encryption with public and private keys, NSec doesn‘t exactly provide what you need. Instead, NSec provides a bunch of low-level primitives (algorithms) that need to be combined into higher-layer solutions (protocols). Getting those combinations right is quite challenging; I would generally recommend against trying that on your own.

You need a specification that tells you how to combine X25519, ChaCha20-Poly1305, and so on. Then you can use NSec to implement that.
