### ISSUE TITLE
Update releases and nuget

### ISSUE THREAD

**Issue by d2dyno1** [ektrah/nsec#63]
The releases haven't been updated recently and now with XChaCha20-Poly1305 supported by the library, I'd like to use it in my project. Unfortunately I'm unable to do it due to the fact that the nuget is still on version 20.2.0 and hasn't been updated since 2020

**Comment by samuel-lucas6** [comment]
There are 3 preview versions on [NuGet](https://www.nuget.org/packages/NSec.Cryptography/22.4.0-preview3) now.

**Comment by ektrah** [comment]
Done. 😃
