### ISSUE TITLE
[Question] how to Export Aes256Gcm key ?

### ISSUE THREAD

**Issue by eveloki** [ektrah/nsec#71]
Like this

https://github.com/ektrah/nsec/issues/8

my code like this 
```
           using var k = NSec.Cryptography.Key.Create(a);

            var text= k.Export(KeyBlobFormat.NSecSymmetricKey);

            var sk = Key.Import(a, text, KeyBlobFormat.NSecSymmetricKey);
```
I try it  ERROR is 
`InvalidOperationException:“The key cannot be exported.”`

**Comment by eveloki** [comment]
I Also Try ChaCha20Poly1305 。

```
var a = AeadAlgorithm.ChaCha20Poly1305;

            using var k =new NSec.Cryptography.Key(a);
            var text = k.Export(KeyBlobFormat.RawSymmetricKey);
```

He still doesn't work。
Why is this thing so complicated。
Isn't it a normal requirement to store the key in the database

**Comment by ektrah** [comment]
A key needs to be created with a suitable policy to be exportable. Have a look at [KeyExportPolicies](https://nsec.rocks/docs/api/nsec.cryptography.keyexportpolicies) and [KeyCreationParameters](https://nsec.rocks/docs/api/nsec.cryptography.keycreationparameters).

**Comment by eveloki** [comment]
thank，I admit I'm a noob (cry:)

but the 'Export' docker the document does not mention relevant policy content at all

like this

`A [KeyCreationParameters](https://nsec.rocks/docs/api/nsec.cryptography.keycreationparameters) value that specifies advanced parameters for the creation of the [Key](https://nsec.rocks/docs/api/nsec.cryptography.key) instance.
`

After reading the document, I didn't realize the influence of this advanced content. my bad
