### ISSUE TITLE
Extended documentation on password hashing

### ISSUE THREAD

**Issue by MartijnFLC** [ektrah/nsec#72]
At this moment I've implemented Libsodium-core. As it is not longer under full development I tried using NSec.

Only for me the documentation is not clear enough how to safely implement it.

In this particular case I'm looking at the password hashing using Argon2id. I scan see a function to create a hash, but no verify function or "needs_rehash" function for example.

Off course I can just hash a user password again and verify the hash, but I guess the verify functions are there for a reason to make sure it doesn't weaken the security.

Is it possible to extend the documentation with examples how to safely hash, verify and/or check if a rehash is needed?

**Comment by ektrah** [comment]
Algorithms such as Argon2id have multiple purposes. One is deriving cryptographic key material from a password; this is what the [PasswordBasedKeyDerivationAlgorithm](https://nsec.rocks/docs/api/nsec.cryptography.passwordbasedkeyderivationalgorithm) class in NSec provides. Another is storing and validating passwords. Libsodium provides a number of functions for this, which however are currently not available in NSec. In principle it's possible to implement these on top of PasswordBasedKeyDerivationAlgorithm, but, as you point out, the functions are there for a reason, so I wouldn't recommend it. Have a look at @samuel-lucas6's [Geralt](https://github.com/samuel-lucas6/Geralt), which does expose these functions and should be easier to upgrade to than NSec.

**Comment by MartijnFLC** [comment]
Thank you for the detailed explanation. I will have a look at Geralt.
Good luck with NSec. Maybe I will use it in the future for different applications.
