### ISSUE TITLE
.NET MAUI - iOS and Android Support

### ISSUE THREAD

**Issue by eugene-viewport** [ektrah/nsec#78]
Can this package support the iOS and Android platforms on .NET MAUI framework?

**Comment by ektrah** [comment]
Version [24.5.0-preview.1](https://github.com/ektrah/nsec/releases/tag/24.5.0-preview.1) has just been released, which brings support for iOS. However, this hasn't been tested yet, so it would be great if you could give it a try. Please provide feedback in #80.

As far as I know, there is no one working on adding support for Android at the moment. Any help is appreciated. 😸
