### ISSUE TITLE
Add support for retrieving the version of Argon2id algorithm used

### ISSUE THREAD

**Issue by egbakou** [ektrah/nsec#79]
I couldn't find a way to retrieve the version of the Argon2id algorithm. It would be useful to have this feature, especially when storing password hashes in a format like: `$AlgorithmName$v=Version$m=MemorySize,t=NumberOfPasses,p=DegreeOfParallelism$Salt$Hash`

**Comment by jedisct1** [comment]
You shouldn't have to create such strings yourself.

Looks like NSec is currently missing bindings for the `crypto_pwhash_str*` functions that are useful for storing password hashes.

**Comment by ektrah** [comment]
NSec currently has no story for hashing passwords to strings, only for deriving keys from passwords. As @jedisct1 wrote, it would be better to use a language binding that exposes libsodium's `crypto_pwhash_str*` APIs than to implement this functionality yourself. Nevertheless, I've exposed the version number in 665e72aa24034509b70acae6d24ac2d37df755c3.

**Comment by egbakou** [comment]
> You shouldn't have to create such strings yourself.
> 
> Looks like NSec is currently missing bindings for the `crypto_pwhash_str*` functions that are useful for storing password hashes.

 @jedisct1 I understand your point about not having to create such strings manually.
 By the way, thanks for your work on libsodium :)

**Comment by egbakou** [comment]
> NSec currently has no story for hashing passwords to strings, only for deriving keys from passwords. As @jedisct1 wrote, it would be better to use a language binding that exposes libsodium's `crypto_pwhash_str*` APIs than to implement this functionality yourself. Nevertheless, I've exposed the version number in [665e72a](https://github.com/ektrah/nsec/commit/665e72aa24034509b70acae6d24ac2d37df755c3).

Thanks for the clarification and the commit @ektrah
