### ISSUE TITLE
Nsec nuget package libsodium 1.20

### ISSUE THREAD

**Issue by gemazzaglia** [ektrah/nsec#83]
Hello, I've executed the last nuget package and it doesn't contain the last libsodium v 1.20. It contains v. 1.19
Can i replace it with the last one? Are you gonna create a new package? 
Thanks.

**Comment by ektrah** [comment]
The package reference has been updated to libsodium 1.0.20 in [NSec 24.9.0-preview.2](https://www.nuget.org/packages/NSec.Cryptography/24.9.0-preview.2).
